# Generated by Django 3.2.8 on 2023-06-08 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_active',
        ),
        migrations.AddField(
            model_name='test',
            name='written_by',
            field=models.ManyToManyField(related_name='written_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
